//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21529664_HW06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_items4 = new HashSet<order_items>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public byte order_status { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime required_date { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public int store_id { get; set; }
        public int staff_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
        public virtual customer customer2 { get; set; }
        public virtual customer customer3 { get; set; }
        public virtual customer customer4 { get; set; }
        public virtual customer customer5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items4 { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
        public virtual staff staff2 { get; set; }
        public virtual staff staff3 { get; set; }
        public virtual staff staff4 { get; set; }
        public virtual staff staff5 { get; set; }
        public virtual staff staff6 { get; set; }
        public virtual staff staff7 { get; set; }
        public virtual staff staff8 { get; set; }
        public virtual staff staff9 { get; set; }
        public virtual staff staff10 { get; set; }
        public virtual staff staff11 { get; set; }
        public virtual staff staff12 { get; set; }
        public virtual staff staff13 { get; set; }
        public virtual staff staff14 { get; set; }
        public virtual staff staff15 { get; set; }
        public virtual store store { get; set; }
        public virtual store store1 { get; set; }
        public virtual store store2 { get; set; }
        public virtual store store3 { get; set; }
        public virtual store store4 { get; set; }
        public virtual store store5 { get; set; }
    }
}
