//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21529664_HW06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int store_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
        public virtual product product2 { get; set; }
        public virtual product product3 { get; set; }
        public virtual product product4 { get; set; }
        public virtual product product5 { get; set; }
        public virtual store store { get; set; }
        public virtual store store1 { get; set; }
        public virtual store store2 { get; set; }
        public virtual store store3 { get; set; }
        public virtual store store4 { get; set; }
        public virtual store store5 { get; set; }
    }
}
